# Задание 3

Данные представлены в следущем формате:
  * $n$ *последовательностей* из векторов размера $params$. 
  * каждому вектору соответствует целевое значение
  * в качестве примера данных такого типа можно использовать код ниже, последовательности векторов - `X_data`, последовательности соответствующих им целевых значений - `y_data`

Требуется реализовать следующую модель генерации батчей данных. Сначала необходимо выбрать вектор данных, равновероятно из всех возможных векторов из данных последовательностей. После чего требуется вернуть батч данных - это матрица размера $batchsize \times params$, центральной строкой которой является выбранный ранее вектор (можем считать, что $batchsize$ - нечетное число), а остальные строки - соответственно соседние с выбранным вектором в его последовательности. В случае, если мы попападаем на границу, последовательность расширяется симметричным отражением строк, более подробно смотрите на примере. Также требуется вернуть соответствующее выбранному вектору целевое значение.

**Пример.** $batchsize=5$, $params=7$
 
Пусть выбран случайный вектор, находящийся в последовательности ниже: 
 
|$P_1$|$P_2$|$P_3$|$P_4$|$P_5$|$P_6$|$P_7$|$target$|
|----:|----:|----:|----:|----:|----:|----:|----:|
|   7 |   2 |   4 |   8 |   9 |   9 |   9 |   1 |
|   2 |   8 |   4 |   2 |   2 |   8 |   1 |   2 |
|   6 |   9 |   7 |   0 |   5 |   6 |   0 |   3 |
|   7 |   4 |   6 |   5 |   3 |   0 |   5 |   4 |
|   1 |   9 |   7 |   5 |   6 |   2 |   5 |   5 |
|   6 |   3 |   5 |   3 |   8 |   3 |   6 |   6 |
|   5 |   2 |   9 |   9 |   9 |   5 |   7 |   7 |

Если выбран пятый вектор, требуется вернуть таблицу ниже и соответстующее ей целевое значение 5.

|$P_1$|$P_2$|$P_3$|$P_4$|$P_5$|$P_6$|$P_7$|
|----:|----:|----:|----:|----:|----:|----:|
|   6 |   9 |   7 |   0 |   5 |   6 |   0 |
|   7 |   4 |   6 |   5 |   3 |   0 |   5 |
|   1 |   9 |   7 |   5 |   6 |   2 |   5 |
|   6 |   3 |   5 |   3 |   8 |   3 |   6 |
|   5 |   2 |   9 |   9 |   9 |   5 |   7 |

 

Если же выбран первый вектор, требуется вернуть таблицу ниже и соответстующее ей целевое значение 1. Обратите внимение, что первые две строки возвращаемой таблицы - соответственно третья и вторая строки исходной последовательности.

|$P_1$|$P_2$|$P_3$|$P_4$|$P_5$|$P_6$|$P_7$|
|----:|----:|----:|----:|----:|----:|----:|
|   6 |   9 |   7 |   0 |   5 |   6 |   0 |
|   2 |   8 |   4 |   2 |   2 |   8 |   1 |
|   7 |   2 |   4 |   8 |   9 |   9 |   9 |
|   2 |   8 |   4 |   2 |   2 |   8 |   1 |
|   6 |   9 |   7 |   0 |   5 |   6 |   0 |

In [1]:
import numpy as np

n = 30
params = 7

sizes = np.random.randint(3, 50, size=n)
X_data = [np.random.randint(0, 10, size=(i, params)) for i in sizes]
y_data = [np.random.randint(10, 20, size=i) for i in sizes]

batch_size = 5

In [2]:
class BatchGenerator(object):
    def __init__(self, X_data, y_data, batch_size, vector):
        self.X_data = X_data
        self.y_data = y_data
        self.batch_size = batch_size
        self.vector = vector
        
        # your code

    def generate(self):
        
        def func_list_invert(item):
            if len(item) <= self.vector:
                return []

            batch_size_list = list(range(self.vector-batch_size//2, self.vector+batch_size//2+1))
            batch_size_list = list(map(lambda x: 0 if x < 0 else x, batch_size_list))
            batch_size_list

            temp_list = list(range(0,len(item)))
            batch_size_list_state = list(map(lambda x: x in temp_list, batch_size_list))

            list_invert = []
            for item2 in list(range(0,len(batch_size_list))):
                if batch_size_list_state[item2] == False:
                    list_invert.append(batch_size_list[len(batch_size_list)-item2-1])
                else:
                    list_invert.append(batch_size_list[item2])
            return list_invert
        
        self.X_data = [[item[i] for i in func_list_invert(item)] for item in X_data]
        self.y_data = [[item[i] for i in func_list_invert(item)] for item in y_data]
        
        return self.X_data, self.y_data
#         your code

In [3]:
batch_generator = BatchGenerator(X_data, y_data, batch_size=7, vector=4)

In [4]:
batch_generator.generate()

([[array([8, 9, 1, 3, 2, 3, 6]),
   array([1, 4, 9, 2, 8, 5, 6]),
   array([1, 2, 3, 6, 9, 8, 4]),
   array([2, 7, 1, 7, 8, 1, 3]),
   array([8, 5, 8, 2, 0, 7, 4])],
  [array([8, 7, 5, 8, 7, 0, 7]),
   array([0, 5, 4, 3, 2, 1, 4]),
   array([3, 3, 3, 0, 9, 3, 8]),
   array([9, 3, 4, 4, 4, 5, 4]),
   array([8, 7, 5, 8, 7, 0, 7])],
  [array([0, 4, 2, 2, 2, 8, 7]),
   array([4, 6, 0, 3, 2, 3, 0]),
   array([0, 3, 8, 4, 1, 3, 4]),
   array([8, 1, 8, 9, 1, 3, 6]),
   array([0, 3, 6, 7, 2, 4, 3])],
  [array([7, 2, 7, 2, 5, 1, 3]),
   array([5, 2, 8, 9, 7, 6, 4]),
   array([0, 0, 9, 9, 2, 3, 0]),
   array([6, 2, 1, 6, 1, 7, 1]),
   array([5, 0, 2, 5, 4, 1, 2])],
  [array([0, 7, 6, 2, 0, 9, 8]),
   array([1, 0, 0, 2, 2, 5, 8]),
   array([1, 0, 8, 6, 9, 8, 8]),
   array([4, 5, 8, 0, 9, 3, 7]),
   array([8, 5, 4, 1, 5, 6, 3])],
  [array([2, 5, 6, 9, 8, 5, 4]),
   array([5, 1, 5, 0, 6, 8, 5]),
   array([4, 0, 0, 4, 4, 2, 8]),
   array([0, 9, 7, 3, 3, 5, 3]),
   array([4, 5, 3, 7, 6, 1, 4])],
  [a